### PR TITLE
Bugfix/adapt to change

### PR DESCRIPTION
**Pull request by ruwang**
This PR addresses two separate problems.

- The file format update (from json to xml) in NDA breaks cron `updateNDAScanType.php`
- Db schema change breaks cron `uploadMotQA.php`. This db schema change was a while ago, as this cron only update the meta when there is something needed to be updated in archive, so it just picked up the change.

After merging this PR, go to chronus:/coins/cron, sudo su coinscron, git pull, then run php command (php $filename) to test (should not see any error message in the console).

### CODE REVIEW

**Comment by mstone121** [comment]
How can I go about testing this?

Also, I noticed that you have the tab setting set to two spaces where much of COINS is four spaces. Was this intentional?

**Comment by ruwang** [comment]
The test instruction is in the PR.

The two spaces tab was intentional. But we should stick to one style, let
me update it.

**Comment by ruwang** [comment]
update pushed.

**Comment by mstone121** [comment]
On chronus:
```
coinscron@chronus:/coins/crons$ php updateNDAScanType.php
PHP Warning:  simplexml_load_file(https://ndar.nih.gov/api/datadictionary/v2/datastructure/image03): failed to open stream: Network is unreachable in /coins/crons/updateNDAScanType.php on line 25
PHP Stack trace:
PHP   1. {main}() /coins/crons/updateNDAScanType.php:0
PHP   2. simplexml_load_file() /coins/crons/updateNDAScanType.php:25
PHP Warning:  simplexml_load_file(): I/O warning : failed to load external entity "https://ndar.nih.gov/api/datadictionary/v2/datastructure/image03" in /coins/crons/updateNDAScanType.php on line 25
PHP Stack trace:
PHP   1. {main}() /coins/crons/updateNDAScanType.php:0
PHP   2. simplexml_load_file() /coins/crons/updateNDAScanType.php:25
PHP Notice:  Trying to get property of non-object in /coins/crons/updateNDAScanType.php on line 26
PHP Stack trace:
PHP   1. {main}() /coins/crons/updateNDAScanType.php:0
PHP Fatal error:  Call to a member function children() on a non-object in /coins/crons/updateNDAScanType.php on line 26
PHP Stack trace:
PHP   1. {main}() /coins/crons/updateNDAScanType.php:0
```
Also, does `uploadMotQA.php` take a really long time?

**Comment by ruwang** [comment]
`Network is unreachable`
This is ok, sometimes it 's hard to reach to that website.


> does uploadMotQA.php take a really long time?
Yes, it takes a while.

**Comment by mstone121** [comment]
Okay, the second time it worked. Should there be some sort of redundancy if this cron tends to be unreliable?

**Comment by ruwang** [comment]
Good point.  The answer is ,It depends. In our micis code, when user does
the NDA mapping, we fetch the info from their website and encounter this
issue as well, and we check its failure and try 5 times until success.

For this particular cron job, it check the scan type update which is
normally quite infrequent. that's why we only run it once a week. So I
won't worry if it fails to fetch once. next time it will catch up.  and it
won't affect micis tool.

**Comment by mstone121** [comment]
Okay, sounds good.

**Pull request merged**
